#!/bin/tcsh



	#This script runs all pre-processing steps for phase one of epi data for all subjects, sessions and runs
	# Require orignal raw NIFTI files, output brain mask files are then edited for use in @afni_prepro_p2

	# Se up path to the data
	set npath = '/Volumes/Seagate_Expansion/natural-connectivity-master/data/RK_DWI_ana'
		cd ${npath}
		foreach subj (AL)
		 cd ${subj}
		  foreach session (S1)
		   cd ${session}
	            foreach run (R1)

		#3dcopy dwi_in_T1.nii.gz ${subj}.${session}.${run}.dti.AL_Raw.nii
		#3dcalc -a ${subj}.${session}.${run}.dti.AL.nii'[3..63]' -expr 'a' -prefix ${subj}.${session}.${run}.dti.AL.Sel.nii
		#3dDWItoDT -prefix DTI.tensors -automask -reweight -verbose 100 -sep_dsets -eigs ../../../DTI/bvecs ${subj}.${session}.${run}.dti.AL.Sel.nii
			#Get single tensors file  
			#3dDWItoDT -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii -automask -reweight -verbose 100 -eigs ../../../DTI/bvecs ${subj}.${session}.${run}.dti.AL.Sel.nii

			#Get FA out  
			#3dcalc -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.V2.nii -a ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii'[9..11]' -c ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii'[18]' -expr 'c*STEP(c)*255*ABS(a)'
			#3dThreetoRGB -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.V2.DTIColorMap.nii -anat ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.V2.nii'[0]' ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.V2.nii'[1]' ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.V2.nii'[2]'

			#3dDWUncert -inset ${subj}.${session}.${run}.dti.AL.Sel.nii -mask brainmask.nii -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii -input DTI.tensors -grads ../../../DTI/bvecs -iters 50


#3dTrackID -mode PROB -dti_in DTI.tensors -netrois BD_cst_l_v3+orig -uncert ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii  -mask brainmask_ed3.nii -alg_Thresh_FA 0.04   -unc_min_FA 0.003   -prefix o.PR_CR_v1

3dTrackID -mode PROB -dti_in DTI.tensors -netrois BD_cst_r_v6+orig -uncert ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii  -mask brainmask_ed3.nii -alg_Thresh_FA 0.04   -unc_min_FA 0.003   -prefix o.PR_CR_r_v3



			#Do whole brain connectivity 
			#3dTrackID -mode DET -dti_in DTI.tensors -netrois brainmask.nii -logic OR -alg_Thresh_Len 5 -do_trk_out  -prefix W.whole_brain_v2

		#cp ../../../spec_files_v2/${subj}/* ./


			#For tracking whole brain on suma
			#3dTrackID -mode DET -dti_in DTI.tensors -netrois ../S1/${subj}.S1.${run}.anat_seg+orig. \
			#-logic OR -alg_Thresh_Len 30  -prefix o.AllROIS
			#3dTrackID -mode DET -dti_in DTI.tensors -netrois ALL_ROIs.Both_RS2+orig. -logic AND -alg_Thresh_Len 30 -prefix All_connectivty

			# Get brain mask 
			#3dAutomask -prefix ../S1/brain_mask ../S1/D99_in_${subj}.S1.${run}.anat_native+orig.

			#3dresample -master ${subj}.${session}.${run}.dti.AL.Sel.nii -prefix ../S1/brain_mask_RS -inset ../S1/brain_mask+orig. 

			#3dresample -master ${subj}.${session}.${run}.dti.AL.Sel.nii -prefix ../S1/ALL_ROIs.Both.RS.nii -inset ../S1/ALL_ROIs.Both.nii  			
			# Get uncertainty  
			#3dDWUncert -inset ${subj}.${session}.${run}.dti.AL.Sel.nii -mask ../S1/brain_mask_RS+orig. \
			#-prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii -input DTI.tensors -grads ../../bvecs -iters 50

			# Do tracking 
			#3dTrackID -mode MINIP -dti_in DTI.tensors -dti_extra ../S1/brain_mask_RS+orig. -netrois ../S1/ALL_ROIs.Both.RS.nii \
			#-logic AND -mini_num 5 -uncert ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii -alg_Thresh_FA 0.45 \
			#-prefix New_tracts_MP_Min5_FA_45_AND_V2


			#rm __temp.*
		   end
		   # Get mean of all mean runs
		   #3dMean -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ${subj}.${session}.*.epi.TZ.VR.SM.U.nii
		   #Get brain mask. The output file was used to create a manullay edited brain mask
		   #3dAutomask -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		   
	           # If you require to make this step by yourself do the following and edit the masks
		   #mkdir mask
		   #3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ./mask/${subj}.${session}.all.epi.mask.nii
		   #3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ./mask/${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		cd ../
	       end
	   cd ../
         end



