#!/bin/tcsh



	#This script runs all pre-processing steps for phase one of epi data for all subjects, sessions and runs
	# Require orignal raw NIFTI files, output brain mask files are then edited for use in @afni_prepro_p2

	# Se up path to the data
	set npath = '/Volumes/Seagate_Expansion/natural-connectivity-master/data/DTI'
		cd ${npath}
		foreach subj (VL)
		 cd ${subj}
		  foreach session (S2)
		   cd ${session}
	            foreach run (R1)
		        # Check if the subject session run file exits otherwise exit loop 
		        #[ -f "${subj}.${session}.${run}.dti.nii" ] && echo 1 || break

			#Create average file
			#3dTshift -tzero 0 -prefix ${subj}.${session}.${run}.epi.TZ.nii  ${subj}.${session}.${run}.epi.nii
		        # 3dcalc -a ${subj}.${session}.${run}.dti.nii'[0..63]' -b ${subj}.${session}.${run}.dti.nii'[64..127]' \
			#-c ${subj}.${session}.${run}.dti.nii'[128..191]' -d ${subj}.${session}.${run}.dti.nii'[192..255]' \
			#-e ${subj}.${session}.${run}.dti.nii'[256..319]' -expr '(a+b+c+d+e)/5' -prefix ${subj}.${session}.avg.dti.nii

			#Align to average 			
			#3dAllineate -base ${subj}.${session}.avg.dti.nii'[0]' -input ${subj}.${session}.${run}.dti.nii \
			#-prefix ${subj}.${session}.${run}.dti.AL.nii -cost mi -verb -EPI

			#Direction selection 
			#3dcalc -a ${subj}.${session}.${run}.dti.AL.nii'[3..63]' -expr 'a' -prefix ${subj}.${session}.${run}.dti.AL.Sel.nii
			
			#Get tensors separate
			#3dDWItoDT -prefix DTI.tensors -automask -reweight -verbose 100 -sep_dsets \
			#-eigs ../../bvecs ${subj}.${session}.${run}.dti.AL.Sel.nii
			
			#Get tensors file  
			#3dDWItoDT -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii -automask -reweight -verbose 100 \
			#-eigs ../../bvecs ${subj}.${session}.${run}.dti.AL.Sel.nii

			#Get FA out  
			#3dcalc -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.nii -a ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii'[9..11]' \
			#-c ${subj}.${session}.${run}.dti.AL.Sel.tensors.nii'[18]' -expr 'c*STEP(c-0.25)*255*ABS(a)'

			#3dThreetoRGB -prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.DTIColorMap.nii \
			#-anat ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.nii'[0]' \
			#${subj}.${session}.${run}.dti.AL.Sel.tensors.out.nii'[1]' ${subj}.${session}.${run}.dti.AL.Sel.tensors.out.nii'[2]'

			#For tracking whole brain on suma
			#3dTrackID -mode DET -dti_in DTI.tensors -netrois ../S1/${subj}.S1.${run}.anat_seg+orig. \
			#-logic OR -alg_Thresh_Len 30  -prefix o.AllROIS
			#3dTrackID -mode DET -dti_in DTI.tensors -netrois ALL_ROIs.Both_RS2+orig. -logic AND -alg_Thresh_Len 30 -prefix All_connectivty

			# Get brain mask 
			3dAutomask -prefix ../S1/brain_mask ../S1/D99_in_${subj}.S1.${run}.anat_native+orig.

			3dresample -master ${subj}.${session}.${run}.dti.AL.Sel.nii -prefix ../S1/brain_mask_RS -inset ../S1/brain_mask+orig. 

			#3dresample -master ${subj}.${session}.${run}.dti.AL.Sel.nii -prefix ../S1/ALL_ROIs.Both.RS.nii -inset ../S1/ALL_ROIs.Both.nii  			
			# Get uncertainty  
			3dDWUncert -inset ${subj}.${session}.${run}.dti.AL.Sel.nii -mask ../S1/brain_mask_RS+orig. \
			-prefix ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii -input DTI.tensors -grads ../../bvecs -iters 50

			# Do tracking 
			3dTrackID -mode MINIP -dti_in DTI.tensors -dti_extra ../S1/brain_mask_RS+orig. -netrois ../S1/ALL_ROIs.Both.RS.nii \
			-logic AND -mini_num 5 -uncert ${subj}.${session}.${run}.dti.AL.Sel.tensors.Uncer.nii -alg_Thresh_FA 0.45 \
			-prefix New_tracts_MP_Min5_FA_45_AND_V2


			#rm __temp.*
		   end
		   # Get mean of all mean runs
		   #3dMean -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ${subj}.${session}.*.epi.TZ.VR.SM.U.nii
		   #Get brain mask. The output file was used to create a manullay edited brain mask
		   #3dAutomask -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		   
	           # If you require to make this step by yourself do the following and edit the masks
		   #mkdir mask
		   #3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ./mask/${subj}.${session}.all.epi.mask.nii
		   #3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ./mask/${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		cd ../
	       end
	   cd ../
         end



