#!/bin/tcsh



#This script runs pre-processing of EPI data for all subjects, sessions and runs
# Require orignal raw NIFTI files, mask files were previously edited and are available for donwload

# Set up the directory for the data
set npath = '/Volumes/Seagate_Expansion/natural-connectivity-master/data/EPI2'
set Xcrop = '10 85'
set Ycrop = '10 84'
set coor = '47 51 26'
set delta = '-1 -1 3'

	cd ${npath}
		foreach subj (AL VL)
			cd ${subj}
  				foreach session (S1)
					cd ${session}/output
					mkdir detrended
					cd detrended

					#******************************Pre-processing part 2********************************************
				    		foreach run (R1 R2 R3 R4 R5)
						        # Check if the subject session run file exits otherwise exit loop 
						        [ -f "../../${subj}.${session}.${run}.epi.nii" ] && echo 1 || break

								#*******************Create final pre-process time series************************

						        3dAutomask -prefix ${subj}.${session}.${run}.brain.mask.nii \
						        ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.U.nii

								3dresample -master ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.U.nii \
								-prefix __tmp_${subj}.${session}.all.epi.WM.RS.nii -inset ../../mask/output/${subj}.${session}.all.epi.WM.nii

								3dresample -master ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.U.nii \
								-prefix __tmp_${subj}.${session}.all.epi.GM.RS.nii -inset ../../mask/output/${subj}.${session}.all.epi.GM.nii
								
								3dmaskave -quiet -mask __tmp_${subj}.${session}.all.epi.WM.RS.nii \
								../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii > ${subj}.${session}.${run}.epi.wm.1D
								
								3dcalc -float -a ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii \
								-b __tmp_${subj}.${session}.all.epi.GM.RS.nii  -expr 'a*b' -prefix ${subj}.${session}.${run}.epi.AL.GM.nii \

								1d_tool.py -infile ../${subj}.${session}.${run}.epi.TZ.DS.mp.1D -set_run_lengths 200 \
								-set_tr 1.5 -derivative -overwrite -write ${subj}.${session}.${run}.derr.1D

								1d_tool.py -infile ../${subj}.${session}.${run}.epi.TZ.DS.mp.1D'[1..6]' -set_nruns 1 \
								-show_censor_count -overwrite -censor_motion 0.1 ${subj}.${session}.${run}

								3dTproject -input ${subj}.${session}.${run}.epi.AL.GM.nii \
								-prefix ${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.TP.nii -censor ${subj}.${session}.${run}_censor.1D \
								-cenmode NTRP -ort ${subj}.${session}.${run}.derr.1D ${subj}.${session}.${run}.epi.wm.1D \
								../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.ica/filtered_func_data.ica/report/ICA_files/selection/not/t*.1D \
								-polort 2 -bandpass 0 0.12 -mask __tmp_${subj}.${session}.all.epi.GM.RS.nii  -blur 2.4 -norm
								
							   	
							   	#*******************Create matrices************************

								#3dresample -master __tmp_${subj}.${session}.all.epi.GM.RS.nii  \
								#-prefix __tmp_${subj}.${session}.R1.anat.NS.New.AL_seg.Q.RS.nii \
								#-inset ../../mask/output/${subj}.${session}.R1.anat.NS.New.AL_seg.Q.nii

								3dresample -master __tmp_${subj}.${session}.all.epi.GM.RS.nii  \
								-prefix __tmp_ALL_ROIs.Both.Q.RS.nii \
								-inset ../../mask/output/ALL_ROIs.Both.Q.nii


								3dNetCorr -inset ${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.TP.nii \
								-mask __tmp_${subj}.${session}.all.epi.GM.RS.nii  \
								-in_rois __tmp_ALL_ROIs.Both.Q.RS.nii \
								-ts_out -ts_label  -prefix ${subj}.${session}.${run}.TS.prepro.nii
						
								rm __tmp_*
							end
							#*******************Calculate TSNR ************************							
							cd ../
							mkdir tsnr
							cd tsnr
							
							3dTcat -prefix ${subj}.${session}.all.epi.AL.GM.nii ../detrended/${subj}.${session}.*.epi.AL.GM.nii

							3dTstat -tsnr -prefix ${subj}.${session}.all.epi.AL.GM.TSNR.nii \
							${subj}.${session}.all.epi.AL.GM.nii

							cp ../../mask/output/${subj}.${session}.all.epi.TZ.VR.SM.U.ZP_shft.AL.nii ./
							cp ../../mask/output/${subj}.${session}.all.epi.GM.nii ./

							IsoSurface -isorois -mergerois ${subj}.${session}.all.epi.GM \
							-input ${subj}.${session}.all.epi.GM.nii -o_gii ${subj}.${session}.all.epi.GM

							@chauffeur_afni                                                       \
							    -ulay  ${subj}.${session}.all.epi.TZ.VR.SM.U.ZP_shft.AL.nii \
							    -olay  ${subj}.${session}.all.epi.AL.GM.TSNR.nii \
							    -cbar hot_black_to_white                                          \
							    -ulay_range 0% 150%                                               \
							    -func_range 100                                                     \
							    -opacity    7                                                     \
							    -pbar_posonly \
							    -prefix figures/figs_${subj}.${session}.TSNR		   \
							    -montx 4 -monty 1                                                 \
							    -set_xhairs SINGLE                                                   \
							    -blowup 3								\
							    -set_ijk ${coor}\
							    -crop_axi_x ${Xcrop} \
				    			-crop_axi_y ${Ycrop} \
							    #-func_resam Bk \
							    -montgap  4 \
							    #-pbar_saveim figs_${subj}.${session}.${state}.colorbar \
							    -montcolor  black \
				    			-delta_slices ${delta} \
							    -label_mode 1 -label_size 3                                       \
							    -image_label_ijk 						\
							    -label_string .${subj} \
							    #-label_mode    OFF \
							    -label_size    1 \
							    -set_xhairs OFF                   \
							    -zerocolor black \
							    -save_ftype PNG 						\
							    -do_clean
								rm figures/figs_*.sag*
								rm figures/figs_*.cor*

					cd ../../../../
	       		end
	   		#cd ../
   		end
   	cd ../





								#3dmaskave -mask ../../mask/output/AL.S1.all.epi.GM.nii AL.S1.R1.epi.TZ.DS.VR.NS.ZP_shft.AL.TSNR2.nii


								#3dDetrend -polort 3 -normalize ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii \
								 #${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.DT.nii

								#3dTstat -tsnr -prefix ${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.DT.TSNR.nii \
								 #${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.DT.nii
								#3dBlurInMask -float -input ${subj}.${session}.${run}.epi.AL.GM.nii \
								#-FWHM 2.4 -mask __tmp_${subj}.${session}.all.epi.GM.RS.nii  -prefix ${subj}.${session}.${run}.epi.AL.GM.SM.nii \
																
								#3dBlurInMask -float -input ../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii \
								#-FWHM 2.4 -mask ${subj}.${session}.${run}.brain.mask.nii  -prefix ${subj}.${session}.${run}.epi.AL.SM.nii \

							#3dTstat -mean -prefix ${subj}.${session}.${run}.epi.AL.MEAN.nii \
							#../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii
							
							#3dTstat -stdevNOD -prefix ${subj}.${session}.${run}.epi.AL.STDV.nii \
							#../${subj}.${session}.${run}.epi.TZ.DS.VR.NS.ZP_shft.AL.nii

							#3dTstat -mean -prefix ${subj}.${session}.${run}.epi.AL.SM.MEAN.nii \
							#${subj}.${session}.${run}.epi.AL.SM.nii
							
							#3dTstat -stdevNOD -prefix ${subj}.${session}.${run}.epi.AL.SM.STDV.nii \
							#${subj}.${session}.${run}.epi.AL.SM.nii

							#3dcalc -a ${subj}.${session}.${run}.epi.AL.MEAN.nii -b ${subj}.${session}.${run}.epi.AL.SM.MEAN.nii \
							#-c ${subj}.${session}.${run}.epi.AL.STDV.nii -d ${subj}.${session}.${run}.epi.AL.SM.STDV.nii \
							#-expr '(abs(a)-abs(b))/(sqrt((c+d))/2)' -prefix ${subj}.${session}.${run}.epi.AL.prepro.effect.nii
		        

	






