#!/bin/tcsh



	#This script runs all pre-processing steps for phase one of epi data for all subjects, sessions and runs
	# Require orignal raw NIFTI files, output brain mask files are then edited for use in @afni_prepro_p2

	# Se up path to the data
	set npath = '~/Desktop/natural-connectivity-master/data/EPI'
		cd ${npath}
		foreach subj (DP VL AL FL)
		 cd ${subj}
		  foreach session (S1)
		   cd ${session}
	            foreach run (R1 R2 R3 R4 R5)
		        # Check if the subject session run file exits otherwise exit loop 
		        [ -f "${subj}.${session}.${run}.epi.nii" ] && echo 1 || break


			#Scale time series by the overall mean (no-smooth data)
			3dcalc -a ${subj}.${session}.${run}.TZ.VR.nii -b ${subj}.${session}.${run}.TZ.VR.U.nii \
			-c ${subj}.${session}.all.mask.nii -expr 'c*min(200, a/b*100)' \
			-float -prefix ${subj}.${session}.${run}.TZ.VR.SN.nii

			#Scale time series by the overall mean (smooth data)
			3dcalc -a ${subj}.${session}.all.TZ.VR.SM.nii -b ${subj}.${session}.${run}.TZ.VR.U.nii \
			-c ${subj}.${session}.all.mask.nii -expr 'c*min(200, a/b*100)' \
			-float -prefix ${subj}.${session}.${run}.TZ.VR.SM.SN.nii

			#1d_tool.py -infile ${subj}${session}.${run}.Tshift.motion.1D -set_run_lengths 200 -set_tr 1.5 -derivative -overwrite -write ${subj}${session}.${run}.derr.1D
	#1d_tool.py -infile ${subj}${session}.${run}.Tshift.NS.motion.1D'[1..6]' -set_nruns 1 -show_censor_count -overwrite -censor_motion 0.1 ${subj}${session}.${run}
	#3dTsmooth -hamming 7 -prefix ${subj}${session}.${run}.Tshift.NS.VR.3FWHM_1.5.Norm.TS ${subj}${session}.${run}.Tshift.NS.VR.3FWHM_1.5.Norm+orig.
	#3dDetrend -prefix ${subj}${session}.${run}.Tshift.NS.VR.3FWHM_1.5.Norm.DT -normalize -polort 3 ${subj}${session}.${run}.Tshift.NS.VR.3FWHM_1.5.Norm+orig.


#Create niml file to do analyses in surface
			rm __temp.*

		      #cd ../
		   end
		   # Get mean of all mean runs
		   3dMean -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ${subj}.${session}.*.epi.TZ.VR.SM.U.nii
		   #Get brain mask. The output file was used to create a manullay edited brain mask
		   3dAutomask -prefix ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		   
	           # If you require to make this step by yourself do the following and edit the masks
		   #mkdir mask
		   3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.M.nii ./mask/${subj}.${session}.all.epi.mask.nii
		   3dcopy ${subj}.${session}.all.epi.TZ.VR.SM.U.nii ./mask/${subj}.${session}.all.epi.TZ.VR.SM.U.nii
		cd ../
	       end
	   cd ../
         end







		        

	






