#!/bin/tcsh



	#This script runs parcelation for all subjects, sessions and runs
	# Require orignal raw NIFTI anat files, output will include segmentation whole brain and right side

	# Se up path to the data
	set npath = '/Volumes/Seagate_Expansion/natural-connectivity-master/data/parc'
	set spath = '/Volumes/Seagate_Expansion/natural-connectivity-master/scripts/prepro_scripts'
	set atlaspath = '/Volumes/Seagate_Expansion/natural-connectivity-master/data/D99_atlas'
	  cd ${npath}
		foreach subj (M1)
		 cd ${subj}
		  foreach session (S1)
		   cd ${session}
	            foreach run (R1)
			3dcopy ${subj}.${session}.${run}.anat.nii ${subj}.${session}.${run}.anat
		        tcsh -x ${spath}/macaque_align.csh ${subj}.${session}.${run}.anat+orig. ${atlaspath}/D99_template.nii.gz \
			${atlaspath}/D99_atlas_1.2a.nii.gz ${atlaspath}/D99_atlas_1.2a_right.nii.gz

			#Do 3dSeg to get white matter segmentation				        
			3dSeg -anat D99_in_${subj}.${session}.${run}.anat_native+orig. -mask AUTO \
			-classes 'CSF ; GM ; WM' -bias_classes 'GM ; WM' -bias_fwhm 25 -mixfrac UNI \
			-main_N 5 -blur_meth BFT
			
		   end
		cd ../
	       end
	   cd ../
         end



			
