#!/bin/tcsh



	#This script runs parcelation for all subjects, sessions and runs
	# Require orignal raw NIFTI anat files, output will include segmentation whole brain and right side

	# Se up path to the data
	set npath = '~/Desktop/natural-connectivity-master/data/segmentation'
	set spath = '~/Desktop/natural-connectivity-master/data/spec_files'
	set fspath = '/Applications/freesurfer/subjects'
	set session = 'S1'
	  cd ${fspath}
		foreach subj (DP VL AL FL) #VL AL FL
		mksubjdirs ${subj} 
		cd ${subj}
		   cd mri
	            #foreach run (R1)
			# copy files and create mgz transform files then run white matter auto-recon		
			3dcopy ${npath}/${subj}/${session}/orig.nii ./orig.nii
			3dcopy ${npath}/${subj}/${session}/T1.nii ./T1.nii			
			3dcopy ${npath}/${subj}/${session}/brain.nii ./brain.nii
			3dcopy ${npath}/${subj}/${session}/brainmask.nii ./brainmask.nii
			3dcopy ${npath}/${subj}/${session}/brainmask.nii ./brainmask.finalsurfs.nii
			3dcopy ${npath}/${subj}/${session}/wm.nii ./wm.nii
			3dcopy ${npath}/${subj}/${session}/filled.nii ./filled.nii

			mri_convert -nt -cs 0.6 brain.nii brain.mgz
			mri_convert -nt -cs 0.6 brain.nii orig.mgz
			mri_convert -nt -cs 0.6 wm.nii wm.mgz
			mri_convert -nt -cs 0.6 filled.nii filled.mgz
			mri_convert -nt -cs 0.6 brainmask.nii brainmask.mgz
			mri_convert -nt -cs 0.6 brainmask.finalsurfs.nii brainmaskfinalsurfs.mgz

			#recon-all -autorecon2-wm -subjid ${subj} -noaseg -nofill -nosegmentation -nonormalization -notalairach -nonuintensitycor 

			mri_tessellate -n $SUBJECTS_DIR/${subj}/mri/filled.mgz 255 $SUBJECTS_DIR/${subj}/surf/rh.orig
			mris_extract_main_component $SUBJECTS_DIR/${subj}/surf/rh.orig $SUBJECTS_DIR/${subj}/surf/rh.white
			mris_smooth -nw $SUBJECTS_DIR/${subj}/surf/rh.white $SUBJECTS_DIR/${subj}/surf/rh.smoothwm
			mris_inflate $SUBJECTS_DIR/${subj}/surf/rh.smoothwm $SUBJECTS_DIR/${subj}/surf/rh.inflated
			mri_tessellate -n $SUBJECTS_DIR/${subj}/mri/filled.mgz 127 $SUBJECTS_DIR/${subj}/surf/lh.orig
			mris_extract_main_component $SUBJECTS_DIR/${subj}/surf/lh.orig $SUBJECTS_DIR/${subj}/surf/lh.white
			mris_smooth -nw $SUBJECTS_DIR/${subj}/surf/lh.white $SUBJECTS_DIR/${subj}/surf/lh.smoothwm
			mris_inflate $SUBJECTS_DIR/${subj}/surf/lh.smoothwm $SUBJECTS_DIR/${subj}/surf/lh.inflated
			#mris_sphere $SUBJECTS_DIR/${subj}/surf/rh.smoothwm $SUBJECTS_DIR/${subj}/surf/rh.inflated
			#mris_sphere $SUBJECTS_DIR/${subj}/surf/rh.smoothwm $SUBJECTS_DIR/${subj}/surf/rh.inflated
			#mris_flatten -w ${iterations} -distances ${size} ${radius} ${in_patch} ${out_patch}
			
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/rh.orig $SUBJECTS_DIR/${subj}/surf/rh.orig.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/rh.white $SUBJECTS_DIR/${subj}/surf/rh.white.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/rh.smoothwm $SUBJECTS_DIR/${subj}/surf/rh.smoothwm.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/rh.inflated $SUBJECTS_DIR/${subj}/surf/rh.inflated.asc
 			mris_convert -c $SUBJECTS_DIR/${subj}/surf/rh.sulc $SUBJECTS_DIR/${subj}/surf/rh.smoothwm $SUBJECTS_DIR/${subj}/surf/rh.sulc.gii
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/lh.orig $SUBJECTS_DIR/${subj}/surf/lh.orig.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/lh.white $SUBJECTS_DIR/${subj}/surf/lh.white.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/lh.smoothwm $SUBJECTS_DIR/${subj}/surf/lh.smoothwm.asc
			mris_convert -o $SUBJECTS_DIR/${subj}/mri/orig.mgz $SUBJECTS_DIR/${subj}/surf/lh.inflated $SUBJECTS_DIR/${subj}/surf/lh.inflated.asc
 			mris_convert -c $SUBJECTS_DIR/${subj}/surf/lh.sulc $SUBJECTS_DIR/${subj}/surf/lh.smoothwm $SUBJECTS_DIR/${subj}/surf/lh.sulc.gii
			cp ../surf/*.asc ${spath}/${subj} 
			3dcopy T1.nii  ${spath}/${subj}/Anat.nii
			mv ../surf/lh.sulc.gii ${spath}/${subj}/lh.sulc.gii.dset 
			mv ../surf/rh.sulc.gii ${spath}/${subj}/rh.sulc.gii.dset 

		     cd ../../
		   end


	
