#!/bin/tcsh



	#This script runs parcelation for all subjects, sessions and runs
	# Require orignal raw NIFTI anat files, output will include segmentation whole brain and right side

	# Se up path to the data
	set npath = '~/Desktop/natural-connectivity-master/data/segmentation'
	  cd ${npath}
		foreach subj (DP VL AL FL)
		 cd ${subj}
		  foreach session (S1)
		   cd ${session}
	            foreach run (R1)

			# copy original anat file, D99_sugrogate and segmentation files		
			3dcopy ../../../surface_files/${subj}/${session}/${subj}.${session}.${run}.anat.NS.New.AL+orig. \
			./${subj}.${session}.${run}.anat.NS.New.AL.nii
			3dcopy ../../../surface_files/${subj}/${session}/D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native+orig \
			./D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii
			3dcopy ../../../surface_files/${subj}/${session}/${subj}.${session}.${run}.anat.NS.New.AL_right_seg+orig \
			./${subj}.${session}.${run}.anat.NS.New.AL_right_seg.nii
			3dcopy ../../../surface_files/${subj}/${session}/${subj}.${session}.${run}.anat.NS.New.AL_seg+orig \
			./${subj}.${session}.${run}.anat.NS.New.AL_seg.nii			
			3dcopy ../../../D99_atlas/pons_mask+orig \
			./__tmp_pons_mask.nii
			3dresample -master ${subj}.${session}.${run}.anat.NS.New.AL.nii \
			-prefix __tmp_pons_mask_RS.nii -inset __tmp_pons_mask.nii			
			
			#get mask from D99_sugrogate and get brain from original				        
			3dcalc -a D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii -expr 'step(a)' \
			-prefix brainmask.nii
		        3dcalc -a ${subj}.${session}.${run}.anat.NS.New.AL.nii -b brainmask.nii \
			-expr 'a*b' -prefix ${subj}.${session}.${run}.anat.NS.New.AL.NS.nii
		        3dcalc -a ${subj}.${session}.${run}.anat.NS.New.AL.NS.nii -b D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii \
			-expr 'a*b' -prefix ${subj}.${session}.${run}.anat.NS.Level2.New.AL.nii			

			#get rid of the cerebelum and the pons on anat data				        
			3dcalc -a ${subj}.${session}.${run}.anat.NS.New.AL_seg.nii -expr 'equals(a,104)' -prefix __tmp_cerebelum
			3dmask_tool -dilate_inputs 1 -1 -fill_holes -fill_dirs xy -prefix __tmp_cerebelum_edit1 -input __tmp_cerebelum+orig.
			3dmask_tool -fill_holes -fill_dirs y -prefix __tmp_cerebelum_edit2 -input __tmp_cerebelum_edit1+orig.
			3dmask_tool -fill_holes -fill_dirs z -prefix __tmp_cerebelum_edit3 -input __tmp_cerebelum_edit2+orig.
			3dcalc -a __tmp_cerebelum_edit3+orig. -b D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii \
			-expr 'a*b' -prefix __tmp_cerebelum_valued.nii
			3dcalc -a __tmp_cerebelum_valued.nii -b D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii \
			-expr 'b-a' -prefix __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.nii
			3dcalc -a __tmp_pons_mask_RS.nii -b __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.nii \
			-expr 'a*b' -prefix __tmp_pons_mask_RS_valued.nii
			3dcalc -a __tmp_pons_mask_RS_valued.nii -b __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.nii \
			-expr 'b-a' -prefix __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.NOpons.nii

			#Do 3dSeg to get white matter segmentation				        
			3dSeg -anat __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.NOpons.nii -mask AUTO \
			-classes 'CSF ; GM ; WM' -bias_classes 'GM ; WM' -bias_fwhm 25 -mixfrac UNI \
			-main_N 5 -blur_meth BFT
			

			#Add the striatum to the wm 				        
			3dcalc -a ./Segsy/Posterior+orig.'[2]' -expr 'ispositive(a-0.5)' -prefix __tmp_wm_ed1.nii
			3dcalc -a ${subj}.${session}.${run}.anat.NS.New.AL_seg.nii -expr 'amongst(a,175,176)' -prefix __tmp_striatum1.nii			
			3dcalc -a __tmp_striatum1.nii -b __tmp_wm_ed1.nii -expr 'step(a+b)' -prefix __tmp_wm_ed2.nii
			
			3dcalc -a __tmp_wm_ed2.nii -b __tmp_D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.NOCeb.NOpons.nii \
			-expr 'a*b' -prefix __tmp_wm_ed2_valued.nii
			3dmerge -1blur_fwhm 1.2 -prefix __tmp_wm_ed2_valued_SM.nii __tmp_wm_ed2_valued.nii
			3dcalc -a __tmp_wm_ed2_valued_SM.nii -expr 'ispositive(a-5)' -prefix __tmp_wm.ted.nii

			3dcalc -a  __tmp_wm.ted.nii -expr 'ispositive(x-0.6)' -prefix __tmp_wm.ted_lh.mask.nii
			3dcalc -a  __tmp_wm.ted.nii -expr 'isnegative(x+0.6)' -prefix __tmp_wm.ted_rh.mask.nii
			3dcalc -a  __tmp_wm.ted.nii  -b __tmp_wm.ted_lh.mask.nii -expr '255*(a*b)' -prefix __tmp_wm.ted_lh.filled.nii
			3dcalc -a  __tmp_wm.ted.nii  -b __tmp_wm.ted_rh.mask.nii -expr '127*(a*b)' -prefix __tmp_wm.ted_rh.filled.nii
			3dcalc -a __tmp_wm.ted_lh.filled.nii -b __tmp_wm.ted_rh.filled.nii -expr 'a+b' -prefix filled.nii
			3dcalc -a  filled.nii -expr 'step(a)' -prefix wm.nii			

			3dcopy ${subj}.${session}.${run}.anat.NS.Level2.New.AL.nii orig.nii
			3dcopy ${subj}.${session}.${run}.anat.NS.Level2.New.AL.nii T1.nii
			3dcopy ${subj}.${session}.${run}.anat.NS.Level2.New.AL.nii brain.nii


			#3dcopy D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii orig.nii
			#3dcopy D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii T1.nii
			#3dcopy D99_in_${subj}.${session}.${run}.anat.NS.New.AL_native.nii brain.nii


			rm ./Segsy/*
			rmdir Segsy
			rm __tmp*
		   end
		cd ../
	       end
	   cd ../
         end

	#mri_convert -nt -cs 0.6 brain.nii brain.mgz
	#mri_convert -nt -cs 0.6 brain.nii orig.mgz
	#mri_convert -nt -cs 0.6 wm.nii wm.mgz
	#mri_convert -nt -cs 0.6 filled.nii filled.mgz
	#mri_convert -nt -cs 0.6 brainmask.nii brainmask.mgz
	#mri_normalize -g 1 -mprage -mask brainmask.mgz brain.mgz brain.finalsurfs.mgz



	
